service: faktubuh
image: ieasybooks/faktubuh

servers:
  web:
    - <%= ENV["SERVER_IP"] %>
  worker:
    hosts:
      - <%= ENV["SERVER_IP"] %>
    cmd: bundle exec good_job start

proxy:
  ssl: true
  hosts:
    - faktubuh.com
    - www.faktubuh.com
  forward_headers: true
  app_port: 3000

registry:
  server: ghcr.io
  username: ieasybooks
  password:
    - KAMAL_REGISTRY_PASSWORD

env:
  secret:
    - RAILS_MASTER_KEY
    - POSTGRES_PASSWORD
  clear:
    WEB_CONCURRENCY: 8
    RUBY_YJIT_ENABLE: "1"
    DB_HOST: faktubuh-postgres18

aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
  dbc: app exec --interactive --reuse "bin/rails dbconsole --include-password"

volumes:
  - "faktubuh_storage:/rails/storage"

asset_path: /rails/public/assets

builder:
  arch: amd64
  cache:
    type: gha
    options: mode=max

accessories:
  postgres18:
    image: postgres:18.1
    roles:
      - web
    env:
      clear:
        POSTGRES_DB: faktubuh_production
        POSTGRES_USER: faktubuh
      secret:
        - POSTGRES_PASSWORD
    cmd: postgres -c "shared_preload_libraries=pg_stat_statements" -c "pg_stat_statements.track=all" -c "pg_stat_statements.max=10000" -c "track_activity_query_size=2048"
    files:
      - db/production.sql:/docker-entrypoint-initdb.d/setup.sql
    directories:
      - data:/var/lib/postgresql
