name: Kamal Run

on:
  workflow_dispatch:
    inputs:
      command:
        description: "Command to run"
        required: true
        type: string
        default: "deploy"

permissions:
  contents: read
  packages: write

jobs:
  kamal-run:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    concurrency:
      group: kamal-run
      cancel-in-progress: false

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v6

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Setup SSH Agent
        uses: webfactory/ssh-agent@v0.9.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Expose GitHub Runtime for cache
        uses: crazy-max/ghaction-github-runtime@v3

      - name: Run bundle exec kamal ${{ github.event.inputs.command }}
        env:
          SERVER_IP: ${{ secrets.SERVER_IP }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        run: |
          bundle exec kamal ${{ github.event.inputs.command }}
